HOSTS:
  centos7-64:
    docker_cmd:
      - "/sbin/init"
    image: centos:8
    platform: el-8-x86_64
    packaging_platform: el-8-x86_64
    docker_image_commands:
      - cp /bin/true /sbin/agetty
      - yum install -y crontabs initscripts iproute openssl wget which
    hypervisor: docker
    roles: []
