---
appveyor.yml:
  delete: true

.gitlab-ci.yml:
  delete: true

.rubocop_todo.yml:
  delete: true

.travis.yml:
  simplecov: true
  deploy: true
  user: jkroepke
  secure: "WiS9j4aI93DobVH/O/z6aHKOY8UL2hwn4+fflKuhvZzJPxfsYYfvQsyX43qetpVAIW7DCZLfO1QQlLF1/ywhe8Y9XRy923R6E7WckYPCGtGBpeTdS7p3Biss2H+ikxI9/5UFlewrdFxLxqgKz8lGLCt8zL1r7ggPWjJBfWEBtk2J9mj4BRTTGt6SWTSHwkdqjloQsPu32SXWY4nsU+87p+lO49YTOH2cS+54/DRCpccPl2AL+kXISDGiDZtlMyGdL2c0Z1e8etmOxbHN2X80YyOQY2GiKdGhzVfx5TDPElDXkOO5JkkZWmsz2D6BJYvu+s9awIJ6/pzGFDghZIK2MSgfUjJd9Vwt1lm48kHKsJ3DsSRIOHK+2ft/3nUl8y7j7KKQMcKKVN35/0uy/cXnD4acuxCh84e5bc0pmYy0gxLhLF6C9Ahv8pls7HhA+jaoUBNXIgCb685w6EgrkaeGMx1vz7VfZo56viod/zZ7XCXg8o5s7vthKMtYLnuGIEl2DvBC3KKtGvl4RnzFVUcZcB5lHgLZozskcwuWFtqd/AgqdIVRzKc6KmRWo8TkE/qOV79MaUpKGONmLMQfsz01HMn4m/NAmu4J55kFgFYkrkwy+9c/3Z9Ytce7goOnyxYYd0fFfaSM8vJCl7oe8Zb3znK2atMmpQAfDwYBwUNe1jU="
  docker_sets:
    - set: docker/ubuntu-18.04
    - set: docker/ubuntu-16.04
    - set: docker/ubuntu-14.04
    - set: docker/debian-9
    - set: docker/debian-8
    - set: docker/centos-7
  docker_defaults:
    bundler_args: '""'
  includes:
    - env: CHECK=clean DEPLOY_TO_FORGE=yes

Gemfile:
  required:
    ':development':
      - gem: 'puppet-lint-absolute_template_path'
      - gem: 'puppet-lint-alias-check'
      - gem: 'puppet-lint-classes_and_types_beginning_with_digits-check'
      - gem: 'puppet-lint-concatenated_template_files-check'
      - gem: 'puppet-lint-file_ensure-check'
      - gem: 'puppet-lint-file_source_rights-check'
      - gem: 'puppet-lint-leading_zero-check'
      - gem: 'puppet-lint-legacy_facts-check'
      - gem: 'puppet-lint-resource_reference_syntax'
      - gem: 'puppet-lint-strict_indent-check'
      - gem: 'puppet-lint-top_scope_facts-check'
      - gem: 'puppet-lint-trailing_comma-check'
      - gem: 'puppet-lint-unquoted_string-check'
      - gem: 'puppet-lint-variable_contains_upcase'
      - gem: 'puppet-lint-version_comparison-check'
    ':system_tests':
      - gem: beaker
        version: '>= 4.2.0'
        from_env: BEAKER_VERSION
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: beaker-docker
      - gem: beaker-puppet
      - gem: beaker-puppet_install_helper
      - gem: beaker-module_install_helper
      - gem: rbnacl
        version: '~> 4.0'
      - gem: rbnacl-libsodium
      - gem: bcrypt_pbkdf
        version: '~> 1.0'

Rakefile:
  default_disabled_lint_checks:
    - 'relative'

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
